/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modules.Reg_user.View;


import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author antonio
 */
public class Create_ruser extends javax.swing.JFrame {

    /**
     * Creates new form Create_admin
     */
    public Create_ruser() {
        ImageIcon icon = new ImageIcon("src/framework_v2/Modules/Reg_user/View/img/wood_3.jpg");
        Image img=icon.getImage();
        Image newimg = img.getScaledInstance(600, 500, java.awt.Image.SCALE_SMOOTH);
        setContentPane(new JLabel(new ImageIcon (newimg)));
    
        initComponents();
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupState = new javax.swing.ButtonGroup();
        fieldDNI = new javax.swing.JTextField();
        labelDNI = new javax.swing.JLabel();
        checkDNI = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        checkName = new javax.swing.JLabel();
        fieldSurname = new javax.swing.JTextField();
        labelSurname = new javax.swing.JLabel();
        checkSurname = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        checkEmail = new javax.swing.JLabel();
        fieldMobile = new javax.swing.JTextField();
        labelMobile = new javax.swing.JLabel();
        checkMobile = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        checkUser = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        checkPassword = new javax.swing.JLabel();
        fieldPassword2 = new javax.swing.JPasswordField();
        labelPassword2 = new javax.swing.JLabel();
        checkPassword2 = new javax.swing.JLabel();
        dateBirth = new com.toedter.calendar.JDateChooser();
        labeldateBitrh = new javax.swing.JLabel();
        checkDatebirth = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        labelAvatar = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();
        radioStateYes = new javax.swing.JRadioButton();
        radioStateNo = new javax.swing.JRadioButton();
        fieldActivity = new javax.swing.JTextField();
        labelActivity = new javax.swing.JLabel();
        checkActivity = new javax.swing.JLabel();
        saving = new javax.swing.JOptionPane();
        areaInfo = new javax.swing.JTextArea();
        btnsaveCreateruser = new javax.swing.JButton();
        btncancelCreateruser = new javax.swing.JButton();
        btnresetCreateruser = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        fieldDNI.setBackground(java.awt.Color.yellow);
        fieldDNI.setToolTipText("");
        getContentPane().add(fieldDNI);
        fieldDNI.setBounds(130, 10, 148, 25);

        labelDNI.setText("ID Card:");
        getContentPane().add(labelDNI);
        labelDNI.setBounds(25, 15, 105, 15);

        checkDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkDNI);
        checkDNI.setBounds(280, 10, 23, 23);

        fieldName.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldName);
        fieldName.setBounds(130, 50, 148, 25);

        labelName.setText("Name:");
        getContentPane().add(labelName);
        labelName.setBounds(25, 50, 105, 15);

        checkName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkName);
        checkName.setBounds(280, 50, 23, 23);

        fieldSurname.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldSurname);
        fieldSurname.setBounds(130, 90, 150, 25);

        labelSurname.setText("Surname:");
        getContentPane().add(labelSurname);
        labelSurname.setBounds(25, 90, 105, 15);

        checkSurname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkSurname);
        checkSurname.setBounds(280, 90, 23, 23);

        fieldEmail.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldEmail);
        fieldEmail.setBounds(130, 130, 150, 25);

        labelEmail.setText("e-mail:");
        getContentPane().add(labelEmail);
        labelEmail.setBounds(25, 130, 105, 15);

        checkEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkEmail);
        checkEmail.setBounds(280, 130, 23, 23);

        fieldMobile.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldMobile);
        fieldMobile.setBounds(130, 170, 150, 25);

        labelMobile.setText("Mobile:");
        getContentPane().add(labelMobile);
        labelMobile.setBounds(25, 170, 105, 15);

        checkMobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkMobile);
        checkMobile.setBounds(280, 170, 23, 23);

        fieldUser.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldUser);
        fieldUser.setBounds(130, 210, 150, 25);

        labelUser.setText("User:");
        getContentPane().add(labelUser);
        labelUser.setBounds(25, 210, 105, 15);

        checkUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkUser);
        checkUser.setBounds(280, 210, 23, 23);

        fieldPassword.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldPassword);
        fieldPassword.setBounds(130, 250, 150, 25);

        labelPassword.setText("Password:");
        getContentPane().add(labelPassword);
        labelPassword.setBounds(25, 250, 105, 15);

        checkPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkPassword);
        checkPassword.setBounds(280, 250, 23, 23);

        fieldPassword2.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldPassword2);
        fieldPassword2.setBounds(130, 290, 150, 25);

        labelPassword2.setText("Verify:");
        getContentPane().add(labelPassword2);
        labelPassword2.setBounds(25, 290, 105, 15);

        checkPassword2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkPassword2);
        checkPassword2.setBounds(280, 290, 23, 23);

        dateBirth.setBackground(java.awt.Color.white);
        dateBirth.setDateFormatString("dd/MM/yyyy");
        dateBirth.setMaxSelectableDate(new java.util.Date(4102444893000L));
        dateBirth.setMinSelectableDate(new java.util.Date(-2208984223000L));
        dateBirth.setName("createdateBirth"); // NOI18N
        dateBirth.setOpaque(false);
        getContentPane().add(dateBirth);
        dateBirth.setBounds(430, 15, 140, 27);
        dateBirth.getAccessibleContext().setAccessibleName(getName());
        dateBirth.getAccessibleContext().setAccessibleDescription(getName());

        labeldateBitrh.setText("Birth date:");
        getContentPane().add(labeldateBitrh);
        labeldateBitrh.setBounds(310, 15, 120, 15);

        checkDatebirth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkDatebirth);
        checkDatebirth.setBounds(580, 15, 23, 23);

        btnSearch.setText("Search");
        getContentPane().add(btnSearch);
        btnSearch.setBounds(380, 90, 90, 29);

        avatar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(avatar);
        avatar.setBounds(490, 60, 100, 100);

        labelAvatar.setText("Avatar:");
        getContentPane().add(labelAvatar);
        labelAvatar.setBounds(310, 90, 90, 15);

        labelState.setText("State: Connected?");
        getContentPane().add(labelState);
        labelState.setBounds(310, 170, 140, 15);

        buttonGroupState.add(radioStateYes);
        radioStateYes.setText("Yes");
        getContentPane().add(radioStateYes);
        radioStateYes.setBounds(470, 170, 60, 22);

        buttonGroupState.add(radioStateNo);
        radioStateNo.setSelected(true);
        radioStateNo.setText("No");
        getContentPane().add(radioStateNo);
        radioStateNo.setBounds(530, 170, 60, 22);

        fieldActivity.setBackground(java.awt.Color.yellow);
        getContentPane().add(fieldActivity);
        fieldActivity.setBounds(430, 210, 114, 25);

        labelActivity.setText("Activity:");
        getContentPane().add(labelActivity);
        labelActivity.setBounds(310, 210, 90, 15);

        checkActivity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkActivity);
        checkActivity.setBounds(580, 210, 23, 23);

        saving.setBorder(null);
        saving.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Reg_user/View/img/Preloader_3.gif"))); // NOI18N
        saving.setMessage("");
        saving.setEnabled(false);
        saving.setFocusable(false);
        saving.setRequestFocusEnabled(false);
        saving.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(saving);
        saving.setBounds(260, 148, 130, 130);

        areaInfo.setColumns(2);
        areaInfo.setRows(1);
        areaInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Info:"));
        getContentPane().add(areaInfo);
        areaInfo.setBounds(65, 330, 490, 50);

        btnsaveCreateruser.setText("Save");
        getContentPane().add(btnsaveCreateruser);
        btnsaveCreateruser.setBounds(140, 400, 100, 29);

        btncancelCreateruser.setText("Cancel");
        getContentPane().add(btncancelCreateruser);
        btncancelCreateruser.setBounds(380, 400, 105, 29);

        btnresetCreateruser.setText("Reset");
        getContentPane().add(btnresetCreateruser);
        btnresetCreateruser.setBounds(265, 400, 100, 29);

        back.setText("back");
        getContentPane().add(back);
        back.setBounds(0, 0, 30, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea areaInfo;
    public static javax.swing.JLabel avatar;
    public static javax.swing.JLabel back;
    public static javax.swing.JButton btnSearch;
    public static javax.swing.JButton btncancelCreateruser;
    public static javax.swing.JButton btnresetCreateruser;
    public static javax.swing.JButton btnsaveCreateruser;
    private javax.swing.ButtonGroup buttonGroupState;
    public static javax.swing.JLabel checkActivity;
    public static javax.swing.JLabel checkDNI;
    public static javax.swing.JLabel checkDatebirth;
    public static javax.swing.JLabel checkEmail;
    public static javax.swing.JLabel checkMobile;
    public static javax.swing.JLabel checkName;
    public static javax.swing.JLabel checkPassword;
    public static javax.swing.JLabel checkPassword2;
    public static javax.swing.JLabel checkSurname;
    public static javax.swing.JLabel checkUser;
    public static com.toedter.calendar.JDateChooser dateBirth;
    public static javax.swing.JTextField fieldActivity;
    public static javax.swing.JTextField fieldDNI;
    public static javax.swing.JTextField fieldEmail;
    public static javax.swing.JTextField fieldMobile;
    public static javax.swing.JTextField fieldName;
    public static javax.swing.JPasswordField fieldPassword;
    public static javax.swing.JPasswordField fieldPassword2;
    public static javax.swing.JTextField fieldSurname;
    public static javax.swing.JTextField fieldUser;
    public static javax.swing.JLabel labelActivity;
    public static javax.swing.JLabel labelAvatar;
    public static javax.swing.JLabel labelDNI;
    public static javax.swing.JLabel labelEmail;
    public static javax.swing.JLabel labelMobile;
    public static javax.swing.JLabel labelName;
    public static javax.swing.JLabel labelPassword;
    public static javax.swing.JLabel labelPassword2;
    public static javax.swing.JLabel labelState;
    public static javax.swing.JLabel labelSurname;
    public static javax.swing.JLabel labelUser;
    public static javax.swing.JLabel labeldateBitrh;
    public static javax.swing.JRadioButton radioStateNo;
    public static javax.swing.JRadioButton radioStateYes;
    public javax.swing.JOptionPane saving;
    // End of variables declaration//GEN-END:variables
}
