/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modules.Menu.View;

/**
 *
 * @author antonio
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkPassword = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        fieldId = new javax.swing.JTextField();
        checkDNI = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        checkPass = new javax.swing.JLabel();
        showPass = new javax.swing.JCheckBox();
        info = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        setEnglish = new javax.swing.JLabel();
        setSpanish = new javax.swing.JLabel();
        setValencian = new javax.swing.JLabel();

        checkPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Admin/View/img/not_ok.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelId.setText("ID:");
        getContentPane().add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 51, 100, -1));
        getContentPane().add(fieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 46, 198, -1));

        checkDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 46, -1, -1));

        labelPass.setText("Password:");
        getContentPane().add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 118, 100, -1));
        getContentPane().add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 113, 198, -1));

        checkPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 117, -1, -1));

        showPass.setText("Show Password");
        getContentPane().add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 146, 190, -1));
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 177, 321, 36));

        btnOk.setText("OK");
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 95, -1));

        btnReset.setText("Reset");
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 80, -1));

        btnCancel.setText("Cancel");
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 95, -1));

        setEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Menu/View/img/ukflag25px.png"))); // NOI18N
        getContentPane().add(setEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        setSpanish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Menu/View/img/SpainFlag25px_2.png"))); // NOI18N
        getContentPane().add(setSpanish, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        setValencian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modules/Menu/View/img/Valflag25px_2.png"))); // NOI18N
        getContentPane().add(setValencian, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCancel;
    public static javax.swing.JButton btnOk;
    public static javax.swing.JButton btnReset;
    public static javax.swing.JLabel checkDNI;
    public static javax.swing.JLabel checkPass;
    public static javax.swing.JLabel checkPassword;
    public static javax.swing.JTextField fieldId;
    public static javax.swing.JPasswordField fieldPass;
    public static javax.swing.JLabel info;
    public static javax.swing.JLabel labelId;
    public static javax.swing.JLabel labelPass;
    public static javax.swing.JLabel setEnglish;
    public static javax.swing.JLabel setSpanish;
    public static javax.swing.JLabel setValencian;
    public static javax.swing.JCheckBox showPass;
    // End of variables declaration//GEN-END:variables
}
