/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework_v2.Modules.Admin.View;


import framework_v2.Modules.Config.Classes.Config_class;
import framework_v2.Modules.Admin.Model.BLL.BLL_admin;
import static framework_v2.Modules.Admin.Model.Classes.Singleton_admin.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author antonio
 */
public class Create_admin extends javax.swing.JFrame {


    
    private void doPause() {
        Timer delay = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
        dispose();
        new Pager_admin().setVisible(true);
            }
        });
        
              
        saving.setVisible(true);
        delay.setRepeats(false);
        delay.start();
        Create_admin.areaInfo.setText("User created correctly");
        Create_admin.areaInfo.setBackground(Color.green);
    }
    
    
    /**
     * Creates new form Create_admin
     */
    public Create_admin() {
        ImageIcon icon = new ImageIcon("src/framework_v2/Modules/Admin/View/img/wood_3.jpg");
        Image img=icon.getImage();
        Image newimg = img.getScaledInstance(600, 500, java.awt.Image.SCALE_SMOOTH);
        setContentPane(new JLabel(new ImageIcon (newimg)));
        
        initComponents();
        saving.setVisible(false);
        this.setResizable(false);
        this.setSize(600,500);//ancho x alto
        dateBirth.setDateFormatString(Config_class.getinstance().getDate_format());
        dateContract.setDateFormatString(Config_class.getinstance().getDate_format());
        Create_admin.dateContract.getDateEditor().setEnabled(false);
        Create_admin.dateBirth.getDateEditor().setEnabled(false);
        Create_admin.dateContract.setEnabled(false);
        Create_admin.areaInfo.setEditable(false);
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                   addWindowListener(new WindowAdapter() {
               @Override
               public void windowClosing(WindowEvent e) {
                    dispose();
                    new Pager_admin().setVisible(true);
               }
           });
        avatar.setIcon(defaultavatar);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupState = new javax.swing.ButtonGroup();
        fieldDNI = new javax.swing.JTextField();
        labelDNI = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelSurname = new javax.swing.JLabel();
        fieldSurname = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldMobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        radioStateYes = new javax.swing.JRadioButton();
        radioStateNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldActivity = new javax.swing.JTextField();
        saveCreateadmin = new javax.swing.JButton();
        cancelCreateadmin = new javax.swing.JButton();
        resetCreateadmin = new javax.swing.JButton();
        checkSurname = new javax.swing.JLabel();
        checkDNI = new javax.swing.JLabel();
        checkName = new javax.swing.JLabel();
        checkEmail = new javax.swing.JLabel();
        checkMobile = new javax.swing.JLabel();
        checkUser = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        checkPassword = new javax.swing.JLabel();
        labelPassword2 = new javax.swing.JLabel();
        fieldPassword2 = new javax.swing.JPasswordField();
        checkPassword2 = new javax.swing.JLabel();
        checkActivity = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        dateBirth = new com.toedter.calendar.JDateChooser();
        dateContract = new com.toedter.calendar.JDateChooser();
        checkDatebirth = new javax.swing.JLabel();
        checkDatecontract = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInfo = new javax.swing.JTextArea();
        saving = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Create Admin");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        fieldDNI.setBackground(java.awt.Color.yellow);
        fieldDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldDNIFocusLost(evt);
            }
        });
        fieldDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldDNIMouseClicked(evt);
            }
        });
        fieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldDNIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldDNIKeyReleased(evt);
            }
        });
        getContentPane().add(fieldDNI);
        fieldDNI.setBounds(90, 10, 148, 25);

        labelDNI.setText("ID Card:");
        getContentPane().add(labelDNI);
        labelDNI.setBounds(10, 15, 70, 15);

        fieldName.setBackground(java.awt.Color.yellow);
        fieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNameFocusLost(evt);
            }
        });
        fieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldNameKeyReleased(evt);
            }
        });
        getContentPane().add(fieldName);
        fieldName.setBounds(90, 50, 148, 25);

        labelName.setText("Name:");
        getContentPane().add(labelName);
        labelName.setBounds(10, 50, 80, 15);

        labelSurname.setText("Surname:");
        getContentPane().add(labelSurname);
        labelSurname.setBounds(10, 90, 80, 15);

        fieldSurname.setBackground(java.awt.Color.yellow);
        fieldSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldSurnameFocusLost(evt);
            }
        });
        fieldSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldSurnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSurnameKeyReleased(evt);
            }
        });
        getContentPane().add(fieldSurname);
        fieldSurname.setBounds(90, 90, 150, 25);

        labelEmail.setText("e-mail:");
        getContentPane().add(labelEmail);
        labelEmail.setBounds(10, 130, 80, 15);

        fieldEmail.setBackground(java.awt.Color.yellow);
        fieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldEmailFocusLost(evt);
            }
        });
        fieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldEmailKeyReleased(evt);
            }
        });
        getContentPane().add(fieldEmail);
        fieldEmail.setBounds(90, 130, 150, 25);

        jLabel5.setText("Mobile:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 80, 15);

        fieldMobile.setBackground(java.awt.Color.yellow);
        fieldMobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldMobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldMobileFocusLost(evt);
            }
        });
        fieldMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldMobileKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldMobileKeyReleased(evt);
            }
        });
        getContentPane().add(fieldMobile);
        fieldMobile.setBounds(90, 170, 150, 25);

        jLabel6.setText("User:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 80, 15);

        fieldUser.setBackground(java.awt.Color.yellow);
        fieldUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldUserFocusLost(evt);
            }
        });
        fieldUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldUserKeyReleased(evt);
            }
        });
        getContentPane().add(fieldUser);
        fieldUser.setBounds(90, 210, 150, 25);

        jLabel7.setText("Password:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 250, 80, 15);

        jLabel9.setText("Birth date:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 15, 90, 15);

        jLabel10.setText("Avatar:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 90, 90, 15);

        jLabel11.setText("State:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 170, 60, 15);

        jLabel12.setText("Connected?");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(343, 170, 90, 15);

        buttonGroupState.add(radioStateYes);
        radioStateYes.setText("Yes");
        getContentPane().add(radioStateYes);
        radioStateYes.setBounds(440, 170, 60, 22);

        buttonGroupState.add(radioStateNo);
        radioStateNo.setSelected(true);
        radioStateNo.setText("No");
        getContentPane().add(radioStateNo);
        radioStateNo.setBounds(500, 170, 60, 22);

        jLabel8.setText("Contract date:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 210, 110, 15);

        jLabel13.setText("Activity:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(290, 250, 90, 15);

        fieldActivity.setBackground(java.awt.Color.yellow);
        fieldActivity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldActivityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldActivityFocusLost(evt);
            }
        });
        fieldActivity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldActivityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldActivityKeyReleased(evt);
            }
        });
        getContentPane().add(fieldActivity);
        fieldActivity.setBounds(400, 250, 114, 25);

        saveCreateadmin.setText("Save");
        saveCreateadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCreateadminActionPerformed(evt);
            }
        });
        getContentPane().add(saveCreateadmin);
        saveCreateadmin.setBounds(140, 400, 80, 29);

        cancelCreateadmin.setText("Cancel");
        cancelCreateadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCreateadminActionPerformed(evt);
            }
        });
        getContentPane().add(cancelCreateadmin);
        cancelCreateadmin.setBounds(360, 400, 90, 29);

        resetCreateadmin.setText("Reset");
        resetCreateadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCreateadminActionPerformed(evt);
            }
        });
        getContentPane().add(resetCreateadmin);
        resetCreateadmin.setBounds(250, 400, 90, 29);

        checkSurname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkSurname);
        checkSurname.setBounds(250, 90, 23, 23);

        checkDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkDNI);
        checkDNI.setBounds(250, 10, 23, 23);

        checkName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkName);
        checkName.setBounds(250, 50, 23, 23);

        checkEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkEmail);
        checkEmail.setBounds(250, 130, 23, 23);

        checkMobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkMobile);
        checkMobile.setBounds(250, 170, 23, 23);

        checkUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkUser);
        checkUser.setBounds(250, 210, 23, 23);

        fieldPassword.setBackground(java.awt.Color.yellow);
        fieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPasswordFocusLost(evt);
            }
        });
        fieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(fieldPassword);
        fieldPassword.setBounds(90, 250, 150, 25);

        checkPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkPassword);
        checkPassword.setBounds(250, 250, 23, 23);

        labelPassword2.setText("Verify:");
        getContentPane().add(labelPassword2);
        labelPassword2.setBounds(10, 290, 80, 15);

        fieldPassword2.setBackground(java.awt.Color.yellow);
        fieldPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPassword2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPassword2FocusLost(evt);
            }
        });
        fieldPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldPassword2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldPassword2KeyReleased(evt);
            }
        });
        getContentPane().add(fieldPassword2);
        fieldPassword2.setBounds(90, 290, 150, 25);

        checkPassword2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkPassword2);
        checkPassword2.setBounds(250, 290, 23, 23);

        checkActivity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkActivity);
        checkActivity.setBounds(550, 250, 23, 23);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(350, 90, 90, 29);

        dateBirth.setBackground(java.awt.Color.white);
        dateBirth.setDateFormatString("dd/MM/yyyy");
        dateBirth.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateBirthPropertyChange(evt);
            }
        });
        getContentPane().add(dateBirth);
        dateBirth.setBounds(400, 15, 140, 27);

        dateContract.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateContractPropertyChange(evt);
            }
        });
        getContentPane().add(dateContract);
        dateContract.setBounds(400, 210, 140, 27);

        checkDatebirth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkDatebirth);
        checkDatebirth.setBounds(550, 15, 23, 23);

        checkDatecontract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/not_ok.png"))); // NOI18N
        getContentPane().add(checkDatecontract);
        checkDatecontract.setBounds(550, 210, 23, 23);

        avatar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(avatar);
        avatar.setBounds(460, 60, 100, 100);

        areaInfo.setColumns(2);
        areaInfo.setRows(1);
        areaInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Info:"));
        jScrollPane1.setViewportView(areaInfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 330, 490, 50);

        saving.setBorder(null);
        saving.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework_v2/Modules/Admin/View/img/Preloader_3.gif"))); // NOI18N
        saving.setMessage("");
        saving.setEnabled(false);
        saving.setFocusable(false);
        saving.setRequestFocusEnabled(false);
        saving.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(saving);
        saving.setBounds(238, 148, 130, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelCreateadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCreateadminActionPerformed
        dispose();
        new Pager_admin().setVisible(true);
    }//GEN-LAST:event_cancelCreateadminActionPerformed

    private void fieldDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldDNIMouseClicked
        BLL_admin.askDniClick();
    }//GEN-LAST:event_fieldDNIMouseClicked

    private void fieldDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDNIKeyPressed
        BLL_admin.askAdmindata("dni");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldName.requestFocus();
        }
    }//GEN-LAST:event_fieldDNIKeyPressed
            
    private void fieldDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDNIKeyReleased
          BLL_admin.askAdmindata("dni");
    }//GEN-LAST:event_fieldDNIKeyReleased

    private void fieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNameKeyPressed
       BLL_admin.askAdmindata("name");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldSurname.requestFocus();
	}
    }//GEN-LAST:event_fieldNameKeyPressed

    private void fieldNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNameKeyReleased
        BLL_admin.askAdmindata("name");
    }//GEN-LAST:event_fieldNameKeyReleased

    private void fieldSurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSurnameKeyPressed
        BLL_admin.askAdmindata("surname");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldEmail.requestFocus();
	}
    }//GEN-LAST:event_fieldSurnameKeyPressed

    private void fieldSurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSurnameKeyReleased
        BLL_admin.askAdmindata("surname");
    }//GEN-LAST:event_fieldSurnameKeyReleased

    private void fieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldEmailKeyPressed
        BLL_admin.askAdmindata("email");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldMobile.requestFocus();
	}
    }//GEN-LAST:event_fieldEmailKeyPressed

    private void fieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldEmailKeyReleased
        BLL_admin.askAdmindata("email");
    }//GEN-LAST:event_fieldEmailKeyReleased

    private void fieldMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMobileKeyPressed
        BLL_admin.askAdmindata("mobile");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldUser.requestFocus();
	}
    }//GEN-LAST:event_fieldMobileKeyPressed

    private void fieldMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMobileKeyReleased
        BLL_admin.askAdmindata("mobile");
    }//GEN-LAST:event_fieldMobileKeyReleased

    private void fieldUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldUserKeyPressed
        BLL_admin.askAdmindata("user");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldPassword.requestFocus();
	}
    }//GEN-LAST:event_fieldUserKeyPressed

    private void fieldUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldUserKeyReleased
        BLL_admin.askAdmindata("user");
    }//GEN-LAST:event_fieldUserKeyReleased

    private void fieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPasswordKeyPressed
        BLL_admin.askAdmindata("password");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldPassword2.requestFocus();
	}
    }//GEN-LAST:event_fieldPasswordKeyPressed

    private void fieldPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPasswordKeyReleased
        BLL_admin.askAdmindata("password");
    }//GEN-LAST:event_fieldPasswordKeyReleased

    private void fieldPassword2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPassword2KeyPressed
        BLL_admin.askAdmindata("password2");
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldActivity.requestFocus();
	}
    }//GEN-LAST:event_fieldPassword2KeyPressed

    private void fieldPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPassword2KeyReleased
        BLL_admin.askAdmindata("password2");
    }//GEN-LAST:event_fieldPassword2KeyReleased

    private void fieldActivityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldActivityKeyPressed
          BLL_admin.askAdmindata("activity");
    }//GEN-LAST:event_fieldActivityKeyPressed

    private void fieldDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDNIFocusGained
         areaInfo.setText("Input a ID card number");
         Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldDNIFocusGained

    private void fieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNameFocusGained
        areaInfo.setText("Input a name");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldNameFocusGained

    private void fieldSurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSurnameFocusGained
        areaInfo.setText("Input a surname");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldSurnameFocusGained

    private void fieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldEmailFocusGained
        areaInfo.setText("Input a e-mail address");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldEmailFocusGained

    private void fieldMobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldMobileFocusGained
        areaInfo.setText("Input a mobile number like 346XXXXXXXX");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldMobileFocusGained

    private void fieldUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUserFocusGained
        areaInfo.setText("Input a user name");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldUserFocusGained

    private void fieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPasswordFocusGained
        areaInfo.setText("Input a password like Az123456 (need a capital letter) 8 letters");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldPasswordFocusGained

    private void fieldPassword2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPassword2FocusGained
        areaInfo.setText("Verify your password");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldPassword2FocusGained

    private void fieldActivityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldActivityFocusGained
        areaInfo.setText("Input the activity");
        Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_fieldActivityFocusGained

    private void fieldDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDNIFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldDNIFocusLost

    private void fieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNameFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldNameFocusLost

    private void fieldSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSurnameFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldSurnameFocusLost

    private void fieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldEmailFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldEmailFocusLost

    private void fieldMobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldMobileFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldMobileFocusLost

    private void fieldUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUserFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldUserFocusLost

    private void fieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPasswordFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldPasswordFocusLost

    private void fieldPassword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPassword2FocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldPassword2FocusLost

    private void fieldActivityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldActivityFocusLost
        areaInfo.setText("");
    }//GEN-LAST:event_fieldActivityFocusLost

    private void resetCreateadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCreateadminActionPerformed
       BLL_admin.resetFields();
    }//GEN-LAST:event_resetCreateadminActionPerformed

    private void dateBirthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateBirthPropertyChange
            BLL_admin.askAdmindata("birthdate");
            Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_dateBirthPropertyChange

    private void dateContractPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateContractPropertyChange
            BLL_admin.askAdmindata("datecontract");
            Create_admin.areaInfo.setBackground(Color.decode("#d6d6d6"));
    }//GEN-LAST:event_dateContractPropertyChange

    private void fieldActivityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldActivityKeyReleased
        BLL_admin.askAdmindata("activity");
    }//GEN-LAST:event_fieldActivityKeyReleased

    private void saveCreateadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCreateadminActionPerformed
        if(BLL_admin.create_admin()==true){
            doPause();
        }
    }//GEN-LAST:event_saveCreateadminActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        BLL_admin.askAdmindata("avatar");
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea areaInfo;
    public static javax.swing.JLabel avatar;
    public static javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroupState;
    private javax.swing.JButton cancelCreateadmin;
    public static javax.swing.JLabel checkActivity;
    public static javax.swing.JLabel checkDNI;
    public static javax.swing.JLabel checkDatebirth;
    public static javax.swing.JLabel checkDatecontract;
    public static javax.swing.JLabel checkEmail;
    public static javax.swing.JLabel checkMobile;
    public static javax.swing.JLabel checkName;
    public static javax.swing.JLabel checkPassword;
    public static javax.swing.JLabel checkPassword2;
    public static javax.swing.JLabel checkSurname;
    public static javax.swing.JLabel checkUser;
    public static com.toedter.calendar.JDateChooser dateBirth;
    public static com.toedter.calendar.JDateChooser dateContract;
    public static javax.swing.JTextField fieldActivity;
    public static javax.swing.JTextField fieldDNI;
    public static javax.swing.JTextField fieldEmail;
    public static javax.swing.JTextField fieldMobile;
    public static javax.swing.JTextField fieldName;
    public static javax.swing.JPasswordField fieldPassword;
    public static javax.swing.JPasswordField fieldPassword2;
    public static javax.swing.JTextField fieldSurname;
    public static javax.swing.JTextField fieldUser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword2;
    private javax.swing.JLabel labelSurname;
    public static javax.swing.JRadioButton radioStateNo;
    public static javax.swing.JRadioButton radioStateYes;
    private javax.swing.JButton resetCreateadmin;
    private javax.swing.JButton saveCreateadmin;
    public javax.swing.JOptionPane saving;
    // End of variables declaration//GEN-END:variables
}
