/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modules.Config.View;

import Modules.Config.DAO.DAO_Config;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author antonio
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config() {
        ImageIcon icon = new ImageIcon("src/Modules/Menu/View/img/blue.jpg");
        Image img=icon.getImage();
        Image newimg = img.getScaledInstance(400, 450, java.awt.Image.SCALE_SMOOTH);
        setContentPane(new JLabel(new ImageIcon (newimg)));
        initComponents();
        
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDateform = new javax.swing.JLabel();
        comboDateform = new javax.swing.JComboBox<>();
        labelCurrency = new javax.swing.JLabel();
        comboCurrency = new javax.swing.JComboBox<>();
        labelLanguage = new javax.swing.JLabel();
        comboLanguage = new javax.swing.JComboBox<>();
        labelFileform = new javax.swing.JLabel();
        comboFileform = new javax.swing.JComboBox<>();
        btnSaveConf = new javax.swing.JButton();
        btnCancelConf = new javax.swing.JButton();
        labelTheme = new javax.swing.JLabel();
        comboTheme = new javax.swing.JComboBox<>();
        labelDecimals = new javax.swing.JLabel();
        comboDecimals = new javax.swing.JComboBox<>();
        btnResetConf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        labelDateform.setText("Date format:");
        getContentPane().add(labelDateform);
        labelDateform.setBounds(60, 36, 110, 15);

        comboDateform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dd/MM/yyyy", "dd-MM-yyyy", "yyyy-MM-dd", "yyyy/MM/dd" }));
        comboDateform.setToolTipText("Choose the date format");
        getContentPane().add(comboDateform);
        comboDateform.setBounds(170, 30, 120, 25);

        labelCurrency.setText("Currency:");
        getContentPane().add(labelCurrency);
        labelCurrency.setBounds(60, 80, 110, 20);

        comboCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euro", "Dollar", "Pound" }));
        comboCurrency.setToolTipText("Choose the currency type");
        getContentPane().add(comboCurrency);
        comboCurrency.setBounds(170, 79, 120, 25);

        labelLanguage.setText("Language:");
        getContentPane().add(labelLanguage);
        labelLanguage.setBounds(60, 130, 110, 15);

        comboLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish", "Valencian" }));
        comboLanguage.setToolTipText("Choose the language");
        getContentPane().add(comboLanguage);
        comboLanguage.setBounds(170, 130, 120, 25);

        labelFileform.setText("File format:");
        getContentPane().add(labelFileform);
        labelFileform.setBounds(60, 180, 110, 15);

        comboFileform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSON", "TXT", "XML" }));
        comboFileform.setToolTipText("Choose the file format");
        getContentPane().add(comboFileform);
        comboFileform.setBounds(170, 180, 120, 25);

        btnSaveConf.setText("Save");
        btnSaveConf.setToolTipText("Save configuration");
        getContentPane().add(btnSaveConf);
        btnSaveConf.setBounds(40, 340, 90, 29);

        btnCancelConf.setText("Cancel");
        btnCancelConf.setToolTipText("Cancel changes and return");
        getContentPane().add(btnCancelConf);
        btnCancelConf.setBounds(275, 340, 90, 29);

        labelTheme.setText("Theme:");
        getContentPane().add(labelTheme);
        labelTheme.setBounds(60, 230, 110, 15);

        comboTheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metal", "Windows", "Motif", "Nimbus", " " }));
        comboTheme.setToolTipText("Choose the theme");
        getContentPane().add(comboTheme);
        comboTheme.setBounds(170, 230, 120, 25);

        labelDecimals.setText("Decimals:");
        getContentPane().add(labelDecimals);
        labelDecimals.setBounds(60, 280, 110, 15);

        comboDecimals.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 decimal", "2 decimals", "3 decimals" }));
        comboDecimals.setToolTipText("Choose the decimal format");
        getContentPane().add(comboDecimals);
        comboDecimals.setBounds(170, 280, 120, 25);

        btnResetConf.setText("Reset");
        btnResetConf.setToolTipText("Reset to defaults");
        getContentPane().add(btnResetConf);
        btnResetConf.setBounds(160, 340, 90, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCancelConf;
    public static javax.swing.JButton btnResetConf;
    public static javax.swing.JButton btnSaveConf;
    public static javax.swing.JComboBox<String> comboCurrency;
    public static javax.swing.JComboBox<String> comboDateform;
    public static javax.swing.JComboBox<String> comboDecimals;
    public static javax.swing.JComboBox<String> comboFileform;
    public static javax.swing.JComboBox<String> comboLanguage;
    public static javax.swing.JComboBox<String> comboTheme;
    public static javax.swing.JLabel labelCurrency;
    public static javax.swing.JLabel labelDateform;
    public static javax.swing.JLabel labelDecimals;
    public static javax.swing.JLabel labelFileform;
    public static javax.swing.JLabel labelLanguage;
    public static javax.swing.JLabel labelTheme;
    // End of variables declaration//GEN-END:variables
}
